/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const EkDateRange: typeof import('epluskit')['EkDateRange']
  const useEkDialog: typeof import('epluskit')['useEkDialog']
}
