/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const EkDateRange: typeof import('epluskit')['EkDateRange']
  const EkOffice: typeof import('epluskit')['EkOffice']
  const EkOnlyOffice: typeof import('epluskit')['EkOnlyOffice']
  const EkTable: typeof import('epluskit')['EkTable']
  const useEkDialog: typeof import('epluskit')['useEkDialog']
}
