/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    DateRangeTest: typeof import('./src/components/DateRangeTest.vue')['default']
    DialogTest: typeof import('./src/components/DialogTest.vue')['default']
    EkDateRange: typeof import('epluskit')['EkDateRange']
    EkTable: typeof import('epluskit')['EkTable']
    TableTest: typeof import('./src/components/TableTest.vue')['default']
    TestDialogContent: typeof import('./src/components/TestDialogContent.vue')['default']
  }
}
